apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  - name: docker-credentials
  - name: empty-dir
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-push
    runAfter: ["fetch-source"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: image-reference
      value: $(params.image-reference)
  - name: deploy
    taskRef:
      name: kubernetes-actions
    runAfter: ["build-push"]
    params:
      - name: script
        value: |
          kubectl apply -f https://raw.githubusercontent.com/mukovozovb/fastapi/main/deployment.yaml
          echo "----------"
          kubectl get deployment
    workspaces:
      - name: kubeconfig-dir
        workspace: empty-dir
      - name: manifest-dir
        workspace: empty-dir